### ISSUE TITLE
invalid SSL Certificate and Basic Auth Problem

### ISSUE THREAD

**Issue by Havrin** [aaw-team/pagenotfoundhandling#1]
Thx for this easy to use pagenotfound handling. I still got 2 Issues.

using a local machine to develop, I don't have a valid SSL Certificate for my local dev domain. Using f.e. https://www.localhost.de results in `Fetching the 404 page failed with error #60: "cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)" ` - TYPO3 Exception
Using http://www.localhost.de works fine though.
Is there a way to fix this? I know, special case but still interested.

Second, and more important, issue comes with the staging environment. In the documentation it says that basic Auth works out of the box. Unfortunately a 404 Page returns a TYPO3 Exception with
`Fetching the 404 page failed with error #: "Client error: GET https://STAGINGDOMAIN/index.php?id=80&loopPrevention=1 resulted in a 401 Unauthorized response: < !DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> < html>< head> < title>401 Unauthorized</title> < /head>< body> Unauth (truncated...) "` (changed quotes etc to not destroy displaying here in the issuetracker)

The Staging Environment has a basic auth with 
AuthType Basic
AuthName "Staging"
AuthUserFile /path/to/.htpasswd
Require valid-user
Order allow,deny
Allow from localhost
Allow from some IPs
Satisfy any

Backend Configuration is just a page id to use. Tried to fill the digest Auth but that did not do anything.

EDIT: Versions would be nice,
TYPO3 8.7.6
RealURL 2.2.1
Multilanguage Project but the langauge does not matter atm

Thx for the help

**Comment by christianfutterlieb** [comment]
Thanks for your report. I'll take care of these issues (most probably) next week and try to release a fix soon, at least for the second problem.

**Comment by Havrin** [comment]
thanks man, really appreciate it. If you need any further information just make a sound.

**Comment by christianfutterlieb** [comment]
@Havrin can you please check the fix in current master? When you're good too I'll release that in TER.

Then: to get your self-signed certificate to work, you need to add following line to your `AdditionalConfiguration.php`:

```
$GLOBALS['TYPO3_CONF_VARS']['HTTP']['verify'] = false;
```

**Warning: do this only in your dev-environment and never ever upload this setting to a public machine!**

**Comment by Havrin** [comment]
@christianfutterlieb Thanks for the work,

On my local machine with your addition to my AdditionalConfiguration everything works fine., Thanks!
On the Staging Environment with a basic auth protection it does not work unfortunately. Do I have to change something?
EDIT: the error is the same as before, 401 Unauthorized response
Also I noticed that with checking and unchecking enabling 404 on the sys_domain record that two tabs for 404 handling show up. The data hold by the second tab is the same as the first tab but without the "enable 404 handling" - checkbox. Not critical, just a hint for the TER release :)
![bildschirmfoto 2017-09-21 um 11 03 32](https://user-images.githubusercontent.com/8169275/30687763-900a053a-9ebc-11e7-9476-924585e8c5ea.png)

**Comment by christianfutterlieb** [comment]
> On the Staging Environment with a basic auth protection it does not work unfortunately. Do I have to change something?

Yes, checkout the current master ;-)

> Also I noticed that with checking and unchecking enabling 404 on the sys_domain record that two tabs for 404 handling show up. The data hold by the second tab is the same as the first tab but without the "enable 404 handling" - checkbox. Not critical, just a hint for the TER release :)

I cannot reproduce this, it is just 'normal' TCA configuration. Try to clear system caches to re-build TCA cache. Note: I'd disable per-domain configuration in ExtensionManager configuration when it's not really needed (say: no multi-domain installation). After doing this, TCA cache must be re-built as well.

**Comment by Havrin** [comment]
I did, running on 2.4.2-dev. But I just overrode it so the TCA sys_template.php was still in place. stupid me. That fixed the double-tab on sys_domain.

Still the basic auth does not work sadly.

**Comment by christianfutterlieb** [comment]
> Still the basic auth does not work sadly.

Can you provide me the error message you get, or a screenshot with the trace?

**Comment by christianfutterlieb** [comment]
@Havrin Just saw that the http headers were not correctly formatted for use with GuzzleHttp and fixed it in current master, plz update

**Comment by Havrin** [comment]
@christianfutterlieb unfortunatly not, double checked if your changes are on the staging env but its still not working.
Additional Info: PHP 7.1, Apache webserver, TYPO3 is now 8.7.7
Here a screen of the whole stack trace:
![screencapture-boll-twt-clients-de-gdgdf-1505992086572](https://user-images.githubusercontent.com/8169275/30693171-a98f6ba0-9ece-11e7-9391-c97acb95fc81.jpg)

**Comment by christianfutterlieb** [comment]
Strange.. can you add following line to https://github.com/aaw-team/pagenotfoundhandling/blob/master/Classes/Controller/PagenotfoundController.php#L629

```
\TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($options);
```
In the debug output you should see an array named 'auth' like so:
```
'auth' => [
    0 => 'your-username',
    1 => 'your-password'
]
```
Is the correct authentication data in there?

**Comment by Havrin** [comment]
@christianfutterlieb I never got to that point and debugged a little bit more and found the issue. I never entered my basic auth credentials because at the basic auth I allow it from my IP to not have to enter my username + password.
AuthType Basic
AuthName "Staging"
AuthUserFile /path/to/.htpasswd
Require valid-user
Order allow,deny
Allow from localhost
Allow from MY_IP
Satisfy any

so $requestHeaders never has an array_key of "Authorization". I never entered the if on line 578. If I remove the line of Allow from MY_IP, I get the prompt to enter my credentials and everything works fine! I don't think this is something you can fix, only by adding another field in the BE for basic auth username and password :/
Thanks for your massive help though! Really appreciate it.

**Comment by christianfutterlieb** [comment]
Alright, now things are much clearer to me. Maybe it works when you enable `sendXForwardedForHeader` in ExtensionManager configuration, see: https://docs.typo3.org/typo3cms/extensions/pagenotfoundhandling/Configuration/ExtensionManager/Index.html#section-http-options

Or maybe you could add `Allow from <your webserver ip>` to the .htaccess file to get it working? I'm not very much into the authorization config of apache. Just as a hint: when you can request your page (not the 404, just any page) directly from the cli of your webserver (eg. with wget), it should work with pnfh too (I guess).

However, your report pointed me to a real existing problem, thus: thanks anyway ;-)

**Comment by Havrin** [comment]
Thank you, I will have a look at it later. Its just a problem for me and not for the user or customer who has to enter the basic auth data, so I don't mind that much.
Glad I could help! Really like it because 404-handling in TYPO3 with multilanguage or multidomain was a pain, now its easy :)

**Comment by Metalicss** [comment]
Hello,
I have a similar problem after upgrading to Typo3 V8.
I hope someone can help me about this.

Typo3: 8.7.7
pagenotfoundhandling: 2.4.2
PHP: 7.0.14

![indir](https://user-images.githubusercontent.com/26469618/31048139-c5166b82-a61f-11e7-9428-b85a51e6f2a7.png)

**Comment by christianfutterlieb** [comment]
@Metalicss It seems you have a 500 error on your 404 page (`/index.php?id=48`). Please check if this page is working correctly first.

**Comment by Metalicss** [comment]
Hello @christianfutterlieb ,
my 404 page working as expected both with realurl (/page-not-found/) and without realurl (/index.php?id=48).

When i use a wrong URL parameter to test the "pagenotfoundhandling" extension, i receive the error above. We have a typo3 website running typo3 V7, all is ok. The problem exist only in our website running Typo3 V8. Maybe that hint helps you.

**Comment by christianfutterlieb** [comment]
> When i use a wrong URL parameter

What do you mean by that? The `loopPrevention=1`? Or do you use `additional404GetParams`? And: can you show me the error you get when using the "wrong URL parameter" please.

**Comment by Metalicss** [comment]
By wrong URL parameter I mean;

For example i try to test the "pagenotfoundhandling" behaviour against a page doesn't exist. And i use a page id which doesn't exist: 
www.mysite.com/index.php?id=155555

Or with realURL:
Our normal page path is www.mysite.com/EN/contact-us/contact-form/
I am testing with : www.mysite.com/EN/contact-us/contact-formmmmmmm/

Then i receive the error i have sent the in my previous message.
In fact i wanted to say that the error occurs when i try to view a page doesn't exist. Just gave these examples.

**Comment by christianfutterlieb** [comment]
Alright.

> my 404 page working as expected

Can you then try to open the URL that gets called by pnfh (it should be `http://www.mysite.com/index.php?id=48&loopPrevention=1`). Then check whether there is an error (it should be) and post it here.

**Comment by Metalicss** [comment]
"http://www.mysite.com/index.php?id=48&loopPrevention=1" is working and no error.

**Comment by christianfutterlieb** [comment]
How can it be then, that calling this URL from within the extension receives a 500 response (according to your screenshot)?

**Comment by Metalicss** [comment]
I really don't know. If you have no idea, then it maybe caused by another extension.
If you want to test it, our website is http://www.mysite.com
You can try to test by calling a wrong path to receive 404 error.

**Comment by christianfutterlieb** [comment]
Please checkout the current master (and clear the system caches). Then go to the extension configuration in ExtensionManager and enable `debugGetUrlError` (tab 'advanced'). Like this you should be able to see the response which pnfh is receiving.

**Comment by Metalicss** [comment]
Christian,
I applied the changes. It seems the problem is caused by the Websop extension (Aimeos) we are using. I guess the response content pointing that extension after changes.

**Comment by christianfutterlieb** [comment]
Oh, that gives me a hint, I think I can fix that. It seems to be a regression bug introduced with 17db1f217c63b7533fd0803407f52d67364b9be5 and not well fixed in 5b9c6b95bc410ee9e5dd3f228967227718ba4af3. I'll push a fix in short time

**Comment by Metalicss** [comment]
Ok, thank you for your kind help.

**Comment by christianfutterlieb** [comment]
Ok, plz pull the current master, it should fix the problem.

**Comment by Metalicss** [comment]
Working like a charm. Thank you for your effort.
Good evening.

**Comment by christianfutterlieb** [comment]
Gr8 ;-)  I'll release an new version with this fix, thanks for reporting!

**Comment by christianfutterlieb** [comment]
Oh: and don't forget to turn off `debugGetUrlError` =)
