### ISSUE TITLE
Error with basic authentication (403 redirect to login page)

### ISSUE THREAD

**Issue by CodeContent** [aaw-team/pagenotfoundhandling#13]
Hi, 

I had a problem with a 403 redirect to a login page.

The site has a basic authentification. I get an error that the curl could not fetch the login page, because of no authentification.

After doing some debug in 
\AawTeam\Pagenotfoundhandling\ErrorHandler\PageErrorHandler::generateErrorPageRequestOptions()

I found that PHP did not get the Authentication Headers. What helped was this comment on
https://www.php.net/manual/de/features.http-auth.php

> Workaround for missing Authorization header under CGI/FastCGI Apache:
> 
> SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0

With this line in htaccess PHP did get the Headers so it worked without any changes.

Perhaps you could add this to documentation.

Thanks
Martin

**Comment by christianfutterlieb** [comment]
Hi @CodeContent 

Thanks for the hint, I'll add that to the docs soon.

Sorry for the delay & regards, Christian

**Comment by christianfutterlieb** [comment]
Added the hint to the troubleshooting page in the wiki (section [Common problems](https://github.com/aaw-team/pagenotfoundhandling/wiki/Troubleshooting#common-problems)).

Next step will be #12
