### ISSUE TITLE
Redirect after login not working anymore

### ISSUE THREAD

**Issue by Patta** [aaw-team/pagenotfoundhandling#14]
With TYPO3 10.4.13 and the extbase felogin plugin, the redirect after 403 login is not working anymore.
It seems that the hidden felogin form element `redirect_url` is not filled with the redirect_url of the pagenotfoundhandling.

pagenotfoundhandling for 403:
errorCode: 403
errorHandler: php
errorPhpClassFQCN:  AawTeam\Pagenotfoundhandling\ErrorHandler\PageErrorHandler
errorPage: page with felogin extbase plugin
additionalGetParams: redirect_url=###CURRENT_URL###

felogin config:
redirectMode = getpost, login, logout
redirectFirstMethod = 1
redirectPageLogin = {$feuserLoginRedirectPid}
redirectPageLoginError =
redirectPageLogout = {$feuserLogoutRedirectPid}

This config was working in TYPO3 9.5 with the pibase felogin plugin. Is this a missing implementation or a bug of pagenotfoundhandling? Thanks for your support.

**Comment by Patta** [comment]
Seems to be a open core issue: https://forge.typo3.org/issues/92068

**Comment by christianfutterlieb** [comment]
Yes, this is related to ext:felogin.

Btw: if you use

    additionalGetParams: return_url=###CURRENT_URL###

it seems to work anyway :-)
