### ISSUE TITLE
If pageUnavailable_force is set, the domain config do not work

### ISSUE THREAD

**Issue by Patta** [aaw-team/pagenotfoundhandling#3]
If pageUnavailable_force is set for maintenance or restriction maybe on a staging system, the specific configuration of a domain do not work. The url debugger show the correct url, but the default template from extension configuration is shown. This happens with 404 and 403 pages. 
If a user is logged in, the 404 page is working, but only with option advanced.preserveFeuserLogin.

My pageUnavailable_force configuration in AdditionalConfiguration.php and with ApplicationContext case 'Production/Staging':
```
$GLOBALS['TYPO3_CONF_VARS']['FE']['pageUnavailable_force'] = 1;
$GLOBALS['TYPO3_CONF_VARS']['FE']['pageUnavailable_handling'] = 'static/accessdenied.html';
$GLOBALS['TYPO3_CONF_VARS']['SYS']['devIPmask'] = '<IPv4>,<IPv6>';
```
`<ipv4P>,<ipv6P>` = dev IPs

Connection: http2, https

**Comment by christianfutterlieb** [comment]
Two things:

1. pnfh is not automatically registered as page **unavailable** handler, but as page **notfound** handler. You can register it for yourself like so: 
    ```php
    $GLOBALS['TYPO3_CONF_VARS']['FE']['pageUnavailable_handling'] = 'USER_FUNCTION:AawTeam\\Pagenotfoundhandling\\Controller\\PagenotfoundController->main';
    ```
    But keep in mind, pnfh will return 400 header instead of 500, which would be appropriate! I'll keep that use case in mind for version 3 ;-)

2. Make sure, the IP of your server is listed in `$GLOBALS['TYPO3_CONF_VARS']['SYS']['devIPmask']` as well. It should work with `127.0.0.1`, at least it did for me in a quick test, but maybe you have to add the "real" IP.

**Comment by Patta** [comment]
@christianfutterlieb Thanks for your answer. Adding the "real" server ip to devIPmask fixed this issue. Thanks!
