### ISSUE TITLE
The composer.json should require typo3/cms-core instead of typo3/cms

### ISSUE THREAD

**Issue by foobar13373** [aaw-team/pagenotfoundhandling#4]
TYPO3 provides a "minimal" setup via composer: `typo3/minimal`. However, this can not be used if any 3rd party extension that is loaded requires the full `typo3/cms` instead of just `typo3/cms-core`.

In fact, pagenotfoundhandling seems to be one of the very last of the "common" extensions that still require the full package. All other common 3rd parties (news, realurl, sourceopt, etc.) only require the core package.

Also, a packagist package would be nice, so that we can actually require the name from your composer.json instead of typo3-ter.

**Comment by christianfutterlieb** [comment]
You're right, I put that back over and over again.. Good time to take care now, thx for the report
