### ISSUE TITLE
TYPO3 9.5 LTS compatibility

### ISSUE THREAD

**Issue by Patta** [aaw-team/pagenotfoundhandling#6]
Currently the TYPO3 9.5 LTS seems not support features like `preserveFeuserLogin` and `additional403GetParams` in the new site error handling. 

Do you plan a release for the 9.5 LTS ? Maybe a implementation for the `PHP` `errorHandler` in the `site_errorhandling` configuration?

Best regards!

**Comment by christianfutterlieb** [comment]
Yes, that's an issue, I know. But I simply didn't have the time to work on pnfh. As of april/may I'll have more time to get back to it.

Btw: I plan to create a whole new version with lots of new features and all the goods from the current, but without the dusty old stuff, see https://github.com/aaw-team/pagenotfoundhandling/wiki/Planning-version-3

**Comment by Patta** [comment]
Great! Please make it avalable also via packagist. Thanks

**Comment by christianfutterlieb** [comment]
@Patta Sry, didn't see that the auto update on packagist stopped working. Fixed now.

Btw: be prepared, I'm about to release version 2.5.1, there's need for a 'fake' errorHandler in order to trigger the old-style error handling.

**Comment by christianfutterlieb** [comment]
Wait, forget my last comment about the 'fake' errorHandler, there's no need for such a thing. Sry for the confusion.
